### ISSUE TITLE
Webhook message sent error in older version of prometheus.

### ISSUE THREAD

**Issue by Kavyeshs41** [bzon/prometheus-msteams#48]
I am using Prometheus v1.5.0 and alertmanager v0.5
it seems like this does not support older versions and throwing below error.

`level=error msg="Failed decoding Prometheus alert message: json: cannot unmarshal number into                                                                               Go struct field PrometheusAlertMessage.groupKey of type string"`

and failing to send message afterwards.

**Comment by Knappek** [comment]
Thanks @Kavyeshs41 for reporting this. Prometheus version 1.5.0 is more than 2 years old, alertmanager 0.5 even older. I don't know whether it makes sense to support these versions. 
Wouldn't it make more sense for you to upgrade prometheus and alertmanager rather than having this implemented in prometheus-msteams?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kavyeshs41** [comment]
Yes definitely i am planning to upgrade both Prometheus and alertmanager.
Thanks.
